<jsp:root 
    xmlns:jsp="http://java.sun.com/JSP/Page"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:form="http://www.springframework.org/tags/form"
    xmlns:s="http://www.springframework.org/tags"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns="http://www.w3.org/1999/xhtml" 
    version="2.0">

<c:url var="base_url" value="http://${pageContext.request.serverName}:${pageContext.request.serverPort}${pageContext.request.contextPath}/" />

<script src="scripts/utils/DOMUtils.js">;</script>

<script src="${base_url}scripts/tutoring/ci_build.js">;</script>
<script language="javascript">
    var serverURL = '${base_url}';
    var ciId = ${curriculumItem.nodeId};
</script>

<div class="glue">
    <fieldset>
        <legend>General Info</legend>
        
        <label>Name</label>
        <div>
            <input type="text" value="${curriculumItem.name}" disabled="disabled" />
        </div>
        
        <label>Weight</label>
        <div>
            <input type="text" value="${curriculumItem.weight}" disabled="disabled" />
        </div>
                
        <label>Description</label>
        <div>
            <textarea disabled="disabled">${curriculumItem.description}</textarea>
        </div>
        <br/>
    </fieldset>
</div>


<div class="glue">
    <fieldset>
        <legend>Entities</legend>

        <div>
            <select id="entityAddSelect">
                <option value="22781">Right Spinalis Cervicis</option>
                <option value="22782">Left Spinalis Cervicis</option>
                <option value="67944">Cerebellum</option>
                <option value="37397">Abductor Digiti Minimi of Left Hand</option>
                <option value="37396">Abductor Digiti Minimi of Right Hand</option>
                <option value="34683">Acromial Part of Left Deltoid</option>
                <option value="34682">Acromial Part of Right Deltoid</option>
                <option value="34681">Clavicular Part of Left Deltoid</option>
                <option value="34691">Clavicular Part of Left Pectoralis Major</option>
                <option value="34690">Clavicular Part of Right Pectoralis Major</option>
                <option value="37399">Flexor Digiti Minimi Brevis of Left Hand</option>
                <option value="37398">Flexor Digiti Minimi Brevis of Right Hand</option>
                <option value="37464">Abductor Digiti Minimi of Left Foot</option>
                <option value="37463">Abductor Digiti Minimi of Right Foot</option>
                <option value="37718">First Lumbrical of Left Foot</option>
                <option value="37698">Lateral Head of Left Triceps Brachii</option>
                <option value="274029">Choroid Plexus of Left Cerebral Hemisphere</option>
                <option value="274027">Choroid Plexus of Right Cerebral Hemisphere</option>
                <option value="40121">Flexor Retinaculum of Left Wrist</option>
                <option value="45875">Abdominal Part of Left Pectoralis Major</option>
                <option value="45874">Abdominal Part of Right Pectoralis Major</option>
                <option value="46305">Anterior Belly of Left Digastric</option>
                <option value="46304">Anterior Belly of Right Digastric</option>
                <option value="61961">Anterior Commissure</option>
                <option value="72909">Anterior Limb of Left Internal Capsule</option>
                <option value="72908">Anterior Limb of Right Internal Capsule</option>
                <option value="7260">Anterior Papillary Muscle of Right Ventricle</option>
                <option value="72801">Anterior Part of Left Superior Temporal Gyrus</option>
                <option value="72800">Anterior Part of Right Superior Temporal Gyrus</option>
                <option value="46768">Aponeurosis of Epicranius</option>
                <option value="14542">Appendix</option>
                <option value="3768">Arch of Aorta</option>
                <option value="3736">Ascending Aorta</option>
                <option value="33583">Ascending Part of Left Trapezius</option>
                <option value="33581">Ascending Part of Right Trapezius</option>
                <option value="12519">Atlas</option>
                <option value="12520">Axis</option>
                <option value="7487">Body of Sternum</option>
                <option value="73464">Brachium of Left Inferior Colliculus</option>
                <option value="73462">Brachium of Left Superior Colliculus</option>
                <option value="73463">Brachium of Right Inferior Colliculus</option>
                <option value="73461">Brachium of Right Superior Colliculus</option>
                <option value="7409">Bronchus</option>
                <option value="50737">Celiac Artery</option>
                <option value="78497">Central Canal of Spinal Cord</option>
                <option value="78467">Cerebral Aqueduct</option>
                <option value="3895">Circumflex Branch of Left Coronary Artery</option>
                <option value="34680">Clavicular Part of Right Deltoid</option>
                <option value="61970">Commissure of Fornix of Forebrain</option>
                <option value="14771">Common Hepatic Artery</option>
                <option value="4706">Coronary Sinus</option>
                <option value="86464">Corpus Callosum</option>
                <option value="19618">Corpus Cavernosum of Penis</option>
                <option value="46111">Deep Head of Left Flexor Pollicis Brevis</option>
                <option value="46110">Deep Head of Right Flexor Pollicis Brevis</option>
                <option value="49005">Deep Part of Left Masseter</option>
                <option value="49004">Deep Part of Right Masseter</option>
                <option value="3784">Descending Aorta</option>
                <option value="33587">Descending Part of Left Trapezius</option>
                <option value="33586">Descending Part of Right Trapezius</option>
                <option value="13295">Diaphragm</option>
                <option value="32651">Distal Phalanx of Left Big Toe</option>
                <option value="32657">Distal Phalanx of Left Fourth Toe</option>
                <option value="23953">Distal Phalanx of Left Index Finger</option>
                <option value="23959">Distal Phalanx of Left Little Finger</option>
                <option value="32659">Distal Phalanx of Left Little Toe</option>
                <option value="23955">Distal Phalanx of Left Middle Finger</option>
                <option value="23957">Distal Phalanx of Left Ring Finger</option>
                <option value="32653">Distal Phalanx of Left Second Toe</option>
                <option value="32655">Distal Phalanx of Left Third Toe</option>
                <option value="23951">Distal Phalanx of Left Thumb</option>
                <option value="32650">Distal Phalanx of Right Big Toe</option>
                <option value="32656">Distal Phalanx of Right Fourth Toe</option>
                <option value="24460">Distal Phalanx of Right Index Finger</option>
                <option value="24463">Distal Phalanx of Right Little Finger</option>
                <option value="32658">Distal Phalanx of Right Little Toe</option>
                <option value="24461">Distal Phalanx of Right Middle Finger</option>
                <option value="24462">Distal Phalanx of Right Ring Finger</option>
                <option value="32652">Distal Phalanx of Right Second Toe</option>
                <option value="32654">Distal Phalanx of Right Third Toe</option>
                <option value="24459">Distal Phalanx of Right Thumb</option>
                <option value="7206">Duodenum</option>
                <option value="52780">Ear</option>
                <option value="9991">Eighth Thoracic Vertebra</option>
                <option value="10059">Eleventh Thoracic Vertebra</option>
                <option value="7131">Esophagus</option>
                <option value="52740">Ethmoid</option>
                <option value="21930">External Anal Sphincter</option>
                <option value="9756">External Intercostal Muscle</option>
                <option value="12513">Eyeball</option>
                <option value="12523">Fifth Cervical Vertebra</option>
                <option value="13076">Fifth Lumbar Vertebra</option>
                <option value="9922">Fifth Thoracic Vertebra</option>
                <option value="13072">First Lumbar Vertebra</option>
                <option value="37717">First Lumbrical of Right Foot</option>
                <option value="37746">First Plantar Interosseous of Left Foot</option>
                <option value="37745">First Plantar Interosseous of Right Foot</option>
                <option value="9165">First Thoracic Vertebra</option>
                <option value="37472">Flexor Digiti Minimi Brevis of Left Foot</option>
                <option value="37471">Flexor Digiti Minimi Brevis of Right Foot</option>
                <option value="40120">Flexor Retinaculum of Right Wrist</option>
                <option value="12522">Fourth Cervical Vertebra</option>
                <option value="13075">Fourth Lumbar Vertebra</option>
                <option value="37484">Fourth Lumbrical of Left Foot</option>
                <option value="37483">Fourth Lumbrical of Right Foot</option>
                <option value="9248">Fourth Thoracic Vertebra</option>
                <option value="78469">Fourth Ventricle</option>
                <option value="76893">Free Taenia</option>
                <option value="52734">Frontal Bone</option>
                <option value="7202">Gallbladder</option>
                <option value="59764">Gingiva of Lower Jaw</option>
                <option value="59763">Gingiva of Upper Jaw</option>
                <option value="18247">Glans Penis</option>
                <option value="4707">Great Cardiac Vein</option>
                <option value="62032">Habenula</option>
                <option value="38618">Humeral Head of Left Flexor Carpi Ulnaris</option>
                <option value="38561">Humeral Head of Left Pronator Teres</option>
                <option value="38617">Humeral Head of Right Flexor Carpi Ulnaris</option>
                <option value="38560">Humeral Head of Right Pronator Teres</option>
                <option value="38639">Humeroulnar Head of Left Flexor Digitorum Superficialis</option>  
                <option value="38638">Humeroulnar Head of Right Flexor Digitorum Superficialis</option>
                <option value="52749">Hyoid Bone</option>
                <option value="7208">Ileum</option>
                <option value="14750">Inferior Mesenteric Artery</option>
                <option value="46288">Inferior Oblique Part of Left Longus Colli</option>
                <option value="46287">Inferior Oblique Part of Right Longus Colli</option>
                <option value="10951">Inferior Vena Cava</option>
                <option value="9758">Innermost Intercostal Muscle</option>
                <option value="9757">Internal Intercostal Muscle</option>
                <option value="23708">Interosseous Membrane of Left Forearm</option>
                <option value="35193">Interosseous Membrane of Left Leg</option>
                <option value="23707">Interosseous Membrane of Right Forearm</option>
                <option value="35192">Interosseous Membrane of Right Leg</option>
                <option value="83740">Interpeduncular Fossa</option>
                <option value="75351">Interventricular Foramen</option>
                <option value="25058">Intervertebral Disk of Axis</option>
                <option value="13505">Intervertebral Disk of Eighth Thoracic Vertebra</option>
                <option value="13508">Intervertebral Disk of Eleventh Thoracic Vertebra</option>
                <option value="13898">Intervertebral Disk of Fifth Cervical Vertebra</option>
                <option value="16037">Intervertebral Disk of Fifth Lumbar Vertebra</option>
                <option value="13502">Intervertebral Disk of Fifth Thoracic Vertebra</option>
                <option value="16033">Intervertebral Disk of First Lumbar Vertebra</option>
                <option value="10458">Intervertebral Disk of First Thoracic Vertebra</option>
                <option value="13897">Intervertebral Disk of Fourth Cervical Vertebra</option>
                <option value="16036">Intervertebral Disk of Fourth Lumbar Vertebra</option>
                <option value="13501">Intervertebral Disk of Fourth Thoracic Vertebra</option>
                <option value="13506">Intervertebral Disk of Ninth Thoracic Vertebra</option>
                <option value="16034">Intervertebral Disk of Second Lumbar Vertebra</option>
                <option value="13495">Intervertebral Disk of Second Thoracic Vertebra</option>
                <option value="13900">Intervertebral Disk of Seventh Cervical Vertebra</option>
                <option value="13504">Intervertebral Disk of Seventh Thoracic Vertebra</option>
                <option value="13899">Intervertebral Disk of Sixth Cervical Vertebra</option>
                <option value="55611">Left Procerus</option>
                <option value="13503">Intervertebral Disk of Sixth Thoracic Vertebra</option>
                <option value="13507">Intervertebral Disk of Tenth Thoracic Vertebra</option>
                <option value="13896">Intervertebral Disk of Third Cervical Vertebra</option>
                <option value="16035">Intervertebral Disk of Third Lumbar Vertebra</option>
                <option value="13500">Intervertebral Disk of Third Thoracic Vertebra</option>
                <option value="13509">Intervertebral Disk of Twelfth Thoracic Vertebra</option>
                <option value="7207">Jejunum</option>
                <option value="61975">Lamina Terminalis</option>
                <option value="45974">Lateral Head of Left Flexor Hallucis Brevis</option>
                <option value="45961">Lateral Head of Left Gastrocnemius</option>
                <option value="45973">Lateral Head of Right Flexor Hallucis Brevis</option>
                <option value="45960">Lateral Head of Right Gastrocnemius</option>
                <option value="37697">Lateral Head of Right Triceps Brachii</option>
                <option value="37460">Left Abductor Hallucis</option>
                <option value="37387">Left Abductor Pollicis Brevis</option>
                <option value="38517">Left Abductor Pollicis Longus</option>
                <option value="72702">Left Accessory Short Gyrus</option>
                <option value="22454">Left Adductor Brevis</option>
                <option value="22457">Left Adductor Longus</option>
                <option value="22460">Left Adductor Magnus</option>
                <option value="43887">Left Adductor Minimus</option>
                <option value="15630">Left Adrenal Gland</option>
                <option value="72833">Left Amygdala</option>
                <option value="37706">Left Anconeus</option>
                <option value="72670">Left Angular Gyrus</option>
                <option value="37669">Left Brachialis</option>
                <option value="4761">Left Brachiocephalic Vein</option>
                <option value="38487">Left Brachioradialis</option>
                <option value="46836">Left Buccinator</option>
                <option value="264844">Left Calcaneal Tendon</option>
                <option value="24498">Left Calcaneus</option>
                <option value="24447">Left Capitate</option>
                <option value="72827">Left Caudate Nucleus</option>
                <option value="81753">Left Cervical Rotator</option>
                <option value="72718">Left Cingulate Gyrus</option>
                <option value="13323">Left Clavicle</option>
                <option value="46444">Left Coccygeus</option>
                <option value="4058">Left Common Carotid Artery</option>
                <option value="14766">Left Common Iliac Artery</option>
                <option value="21388">Left Common Iliac Vein</option>
                <option value="37666">Left Coracobrachialis</option>
                <option value="46797">Left Corrugator Supercilii</option>
                <option value="24529">Left Cuboid Bone</option>
                <option value="19236">Left Deferent Duct</option>
                <option value="46830">Left Depressor Anguli Oris</option>
                <option value="46818">Left Depressor Labii Inferioris</option>
                <option value="55609">Left Depressor Septi Nasi</option>
                <option value="8310">Left Eighth Rib</option>
                <option value="8532">Left Eleventh Rib</option>
                <option value="18257">Left Epididymis</option>
                <option value="38499">Left Extensor Carpi Radialis Brevis</option>
                <option value="38496">Left Extensor Carpi Radialis Longus</option>
                <option value="38505">Left Extensor Digiti Minimi</option>
                <option value="38502">Left Extensor Digitorum</option>
                <option value="51143">Left Extensor Digitorum Brevis</option>
                <option value="22549">Left Extensor Digitorum Longus</option>
                <option value="51145">Left Extensor Hallucis Brevis</option>
                <option value="22547">Left Extensor Hallucis Longus</option>
                <option value="38526">Left Extensor Indicis</option>
                <option value="38520">Left Extensor Pollicis Brevis</option>
                <option value="38523">Left Extensor Pollicis Longus</option>
                <option value="18807">Left External Iliac Artery</option>
                <option value="18886">Left External Iliac Vein</option>
                <option value="13337">Left External Oblique</option>
                <option value="24475">Left Femur</option>
                <option value="24481">Left Fibula</option>
                <option value="7212">Left Testis</option>
                <option value="22555">Left Fibularis Brevis</option>
                <option value="22553">Left Fibularis Longus</option>
                <option value="22551">Left Fibularis Tertius</option>
                <option value="8112">Left Fifth Costal Cartilage</option>
                <option value="24473">Left Fifth Metacarpal Bone</option>
                <option value="24516">Left Fifth Metatarsal Bone</option>
                <option value="8093">Left Fifth Rib</option>
                <option value="8005">Left First Costal Cartilage</option>
                <option value="24465">Left First Metacarpal Bone</option>
                <option value="24508">Left First Metatarsal Bone</option>
                <option value="7987">Left First Rib</option>
                <option value="37466">Left Flexor Accessorius</option>
                <option value="38461">Left Flexor Carpi Radialis</option>
                <option value="37462">Left Flexor Digitorum Brevis</option>
                <option value="65017">Left Flexor Digitorum Longus</option>
                <option value="38480">Left Flexor Digitorum Profundus</option>
                <option value="258716">Left Thalamus</option>
                <option value="65015">Left Flexor Hallucis Longus</option>
                <option value="38484">Left Flexor Pollicis Longus</option>
                <option value="72925">Left Fornix of Forebrain</option>
                <option value="8167">Left Fourth Costal Cartilage</option>
                <option value="24471">Left Fourth Metacarpal Bone</option>
                <option value="24514">Left Fourth Metatarsal Bone</option>
                <option value="8148">Left Fourth Rib</option>
                <option value="46760">Left Frontalis</option>
                <option value="72690">Left Fusiform Gyrus</option>
                <option value="14768">Left Gastric Artery</option>
                <option value="22337">Left Gemellus Inferior</option>
                <option value="22335">Left Gemellus Superior</option>
                <option value="46327">Left Geniohyoid</option>
                <option value="72831">Left Globus Pallidus</option>
                <option value="22329">Left Gluteus Maximus</option>
                <option value="22331">Left Gluteus Medius</option>
                <option value="22333">Left Gluteus Minimus</option>
                <option value="43884">Left Gracilis</option>
                <option value="24449">Left Hamate</option>
                <option value="16587">Left Hip Bone</option>
                <option value="72714">Left Hippocampus</option>
                <option value="23131">Left Humerus</option>
                <option value="22323">Left Iliacus</option>
                <option value="45859">Left Iliococcygeus</option>
                <option value="22745">Left Iliocostalis Cervicis</option>
                <option value="22741">Left Iliocostalis Lumborum</option>
                <option value="22743">Left Iliocostalis Thoracis</option>
                <option value="58777">Left Iliotibial Tract</option>
                <option value="73435">Left Inferior Colliculus</option>
                <option value="54738">Left Inferior Nasal Concha</option>
                <option value="72688">Left Inferior Temporal Gyrus</option>
                <option value="32548">Left Infraspinatus Muscle</option>
                <option value="21965">Left Inguinal Ligament</option>
                <option value="72978">Left Insula</option>
                <option value="24524">Left Intermediate Cuneiform Bone</option>
                <option value="264840">Left Intermediate Tendon</option>
                <option value="18810">Left Internal Iliac Artery</option>
                <option value="18888">Left Internal Iliac Vein</option>
                <option value="4762">Left Internal Jugular Vein</option>
                <option value="13893">Left Internal Oblique</option>
                <option value="7205">Left Kidney</option>
                <option value="53646">Left Lacrimal Bone</option>
                <option value="24526">Left Lateral Cuneiform Bone</option>
                <option value="73304">Left Lateral Geniculate Body</option>
                <option value="78450">Left Lateral Ventricle</option>
                <option value="13359">Left Latissimus Dorsi</option>
                <option value="46824">Left Levator Anguli Oris</option>
                <option value="46807">Left Levator Labii Superioris</option>
                <option value="46804">Left Levator Labii Superioris Alaeque Nasi</option>
                <option value="32541">Left Levator Scapulae</option>
                <option value="71195">Left Lobe of Thymus</option>
                <option value="44250">Left Long Plantar Ligament</option>
                <option value="22756">Left Longissimus Capitis</option>
                <option value="22758">Left Longissimus Cervicis</option>
                <option value="22753">Left Longissimus Thoracis</option>
                <option value="46310">Left Longus Capitis</option>
                <option value="57143">Left Lower Central Secondary Incisor Tooth</option>
                <option value="55704">Left Lower First Secondary Molar Tooth</option>
                <option value="55693">Left Lower First Secondary Premolar Tooth</option>
                <option value="57141">Left Lower Lateral Secondary Incisor Tooth</option>
                <option value="55703">Left Lower Second Secondary Molar Tooth</option>
                <option value="55692">Left Lower Second Secondary Premolar Tooth</option>
                <option value="55687">Left Lower Secondary Canine Tooth</option>
                <option value="23090">Left Lumbar Rotator</option>
                <option value="24438">Left Lunate</option>
                <option value="53650">Left Maxilla</option>
                <option value="24522">Left Medial Cuneiform Bone</option>
                <option value="22359">Left Semitendinosus</option>
                <option value="73310">Left Medial Geniculate Body</option>
                <option value="49013">Left Medial Pterygoid</option>
                <option value="46827">Left Mentalis</option>
                <option value="72656">Left Middle Frontal Gyrus</option>
                <option value="72686">Left Middle Temporal Gyrus</option>
                <option value="22879">Left Multifidus</option>
                <option value="46322">Left Mylohyoid</option>
                <option value="53648">Left Nasal Bone</option>
                <option value="55607">Left Nasalis</option>
                <option value="8391">Left Ninth Rib</option>
                <option value="32537">Left Obliquus Capitis Inferior</option>
                <option value="32535">Left Obliquus Capitis Superior</option>
                <option value="22327">Left Obturator Externus</option>
                <option value="22325">Left Obturator Internus</option>
                <option value="72976">Left Occipital Lobe</option>
                <option value="46762">Left Occipitalis</option>
                <option value="13349">Left Omohyoid</option>
                <option value="37391">Left Opponens Pollicis</option>
                <option value="50878">Left Optic Nerve</option>
                <option value="67936">Left Optic Tract</option>
                <option value="53656">Left Palatine Bone</option>
                <option value="38464">Left Palmaris Longus</option>
                <option value="72706">Left Parahippocampal Gyrus</option>
                <option value="52789">Left Parietal Bone</option>
                <option value="24487">Left Patella</option>
                <option value="22451">Left Pectineus</option>
                <option value="13376">Left Pectoralis Minor</option>
                <option value="22341">Left Piriformis</option>
                <option value="24442">Left Pisiform</option>
                <option value="22561">Left Plantaris</option>
                <option value="45740">Left Platysma</option>
                <option value="22592">Left Popliteus</option>
                <option value="72666">Left Postcentral Gyrus</option>
                <option value="72662">Left Precentral Gyrus</option>
                <option value="38455">Left Pronator Quadratus</option>
                <option value="22343">Left Psoas Major</option>
                <option value="45855">Left Pubococcygeus</option>
                <option value="45857">Left Puborectalis</option>
                <option value="72829">Left Putamen</option>
                <option value="22347">Left Pyramidalis</option>
                <option value="22339">Left Quadratus Femoris</option>
                <option value="22349">Left Quadratus Lumborum</option>
                <option value="23465">Left Radius</option>
                <option value="13378">Left Rectus Abdominis</option>
                <option value="46314">Left Rectus Capitis Anterior</option>
                <option value="46318">Left Rectus Capitis Lateralis</option>
                <option value="32531">Left Rectus Capitis Posterior Major</option>
                <option value="32533">Left Rectus Capitis Posterior Minor</option>
                <option value="38929">Left Rectus Femoris</option>
                <option value="14753">Left Renal Artery</option>
                <option value="14336">Left Renal Vein</option>
                <option value="13382">Left Rhomboid Major</option>
                <option value="13384">Left Rhomboid Minor</option>
                <option value="46840">Left Risorius</option>
                <option value="22355">Left Sartorius</option>
                <option value="13393">Left Scalenus Anterior</option>
                <option value="13391">Left Scalenus Medius</option>
                <option value="13389">Left Scalenus Posterior</option>
                <option value="24436">Left Scaphoid</option>
                <option value="13396">Left Scapula</option>
                <option value="8031">Left Second Costal Cartilage</option>
                <option value="24467">Left Second Metacarpal Bone</option>
                <option value="24510">Left Second Metatarsal Bone</option>
                <option value="8012">Left Second Rib</option>
                <option value="22449">Left Semimembranosus</option>
                <option value="19388">Left Seminal Vesicle</option>
                <option value="22877">Left Semispinalis Capitis</option>
                <option value="22875">Left Semispinalis Cervicis</option>
                <option value="22873">Left Semispinalis Thoracis</option>
                <option value="13399">Left Serratus Anterior</option>
                <option value="13406">Left Serratus Posterior Inferior</option>
                <option value="13404">Left Serratus Posterior Superior</option>
                <option value="8275">Left Seventh Costal Cartilage</option>
                <option value="8256">Left Seventh Rib</option>
                <option value="8221">Left Sixth Costal Cartilage</option>
                <option value="8202">Left Sixth Rib</option>
                <option value="22559">Left Soleus</option>
                <option value="22780">Left Spinalis Thoracis</option>
                <option value="22729">Left Splenius Capitis</option>
                <option value="22727">Left Splenius Cervicis</option>
                <option value="13409">Left Sternocleidomastoid</option>
                <option value="13347">Left Sternohyoid</option>
                <option value="13351">Left Sternothyroid</option>
                <option value="73414">Left Stria Medullaris of Thalamus</option>
                <option value="72940">Left Stria Terminalis</option>
                <option value="45827">Left Stylohyoid</option>
                <option value="4694">Left Subclavian Artery</option>
                <option value="4763">Left Subclavian Vein</option>
                <option value="13411">Left Subclavius</option>
                <option value="13415">Left Subscapularis</option>
                <option value="73423">Left Superior Colliculus</option>
                <option value="72654">Left Superior Frontal Gyrus</option>
                <option value="38514">Left Supinator</option>
                <option value="72668">Left Supramarginal Gyrus</option>
                <option value="32545">Left Supraspinatus</option>
                <option value="24483">Left Talus</option>
                <option value="52739">Left Temporal Bone</option>
                <option value="49008">Left Temporalis</option>
                <option value="46764">Left Temporoparietalis</option>
                <option value="22426">Left Tensor Fasciae Latae</option>
                <option value="8472">Left Tenth Rib</option>
                <option value="32552">Left Teres Major</option>
                <option value="32554">Left Teres Minor</option>
                <option value="8058">Left Third Costal Cartilage</option>
                <option value="24469">Left Third Metacarpal Bone</option>
                <option value="24512">Left Third Metatarsal Bone</option>
                <option value="8039">Left Third Rib</option>
                <option value="13353">Left Thyrohyoid</option>
                <option value="24478">Left Tibia</option>
                <option value="22545">Left Tibialis Anterior</option>
                <option value="65019">Left Tibialis Posterior</option>
                <option value="22345">Left Transversus Abdominis</option>
                <option value="9762">Left Transversus Thoracis</option>
                <option value="24444">Left Trapezium</option>
                <option value="24445">Left Trapezoid</option>
                <option value="24440">Left Triquetral</option>
                <option value="8534">Left Twelfth Rib</option>
                <option value="23468">Left Ulna</option>
                <option value="55682">Left Upper Central Secondary Incisor Tooth</option>
                <option value="55699">Left Upper First Secondary Molar Tooth</option>
                <option value="55690">Left Upper First Secondary Premolar Tooth</option>
                <option value="55683">Left Upper Lateral Secondary Incisor Tooth</option>
                <option value="55700">Left Upper Second Secondary Molar Tooth</option>
                <option value="55691">Left Upper Second Secondary Premolar Tooth</option>
                <option value="55799">Left Upper Secondary Canine Tooth</option>
                <option value="15572">Left Ureter</option>
                <option value="38935">Left Vastus Intermedius</option>
                <option value="38931">Left Vastus Lateralis</option>
                <option value="38933">Left Vastus Medialis</option>
                <option value="52893">Left Zygomatic Bone</option>
                <option value="46813">Left Zygomaticus Major</option>
                <option value="46815">Left Zygomaticus Minor</option>
                <option value="11336">Linea Alba</option>
                <option value="7197">Liver</option>
                <option value="37687">Long Head of Left Biceps Brachii</option>
                <option value="45889">Long Head of Left Biceps Femoris</option>
                <option value="37700">Long Head of Left Triceps Brachii</option>
                <option value="37686">Long Head of Right Biceps Brachii</option>
                <option value="45888">Long Head of Right Biceps Femoris</option>
                <option value="37699">Long Head of Right Triceps Brachii</option>
                <option value="49023">Lower Head of Left Lateral Pterygoid</option>
                <option value="49022">Lower Head of Right Lateral Pterygoid</option>
                <option value="7371">Lower Lobe of Left Lung</option>
                <option value="7337">Lower Lobe of Right Lung</option>
                <option value="74877">Mammillary Body</option>
                <option value="52748">Mandible</option>
                <option value="7486">Manubrium</option>
                <option value="3818">Marginal Branch of Right Coronary Artery</option>
                <option value="45972">Medial Head of Left Flexor Hallucis Brevis</option>
                <option value="45958">Medial Head of Left Gastrocnemius</option>
                <option value="37696">Medial Head of Left Triceps Brachii</option>
                <option value="45971">Medial Head of Right Flexor Hallucis Brevis</option>
                <option value="45957">Medial Head of Right Gastrocnemius</option>
                <option value="37695">Medial Head of Right Triceps Brachii</option>
                <option value="62004">Medulla Oblongata</option>
                <option value="76891">Mesocolic Taenia</option>
                <option value="46841">Orbicularis Oris</option>
                <option value="4713">Middle Cardiac Vein</option>
                <option value="7383">Middle Lobe of Lung</option>
                <option value="32647">Middle Phalanx of Left Fourth Toe</option>
                <option value="23938">Middle Phalanx of Left Index Finger</option>
                <option value="23944">Middle Phalanx of Left Little Finger</option>
                <option value="230988">Middle Phalanx of Left Little Toe</option>
                <option value="23940">Middle Phalanx of Left Middle Finger</option>
                <option value="23942">Middle Phalanx of Left Ring Finger</option>
                <option value="32643">Middle Phalanx of Left Second Toe</option>
                <option value="32645">Middle Phalanx of Left Third Toe</option>
                <option value="32646">Middle Phalanx of Right Fourth Toe</option>
                <option value="24455">Middle Phalanx of Right Index Finger</option>
                <option value="24458">Middle Phalanx of Right Little Finger</option>
                <option value="230986">Middle Phalanx of Right Little Toe</option>
                <option value="24456">Middle Phalanx of Right Middle Finger</option>
                <option value="24457">Middle Phalanx of Right Ring Finger</option>
                <option value="32642">Middle Phalanx of Right Second Toe</option>
                <option value="32644">Middle Phalanx of Right Third Toe</option>
                <option value="7235">Mitral Valve</option>
                <option value="24501">Navicular Bone of Left Foot</option>
                <option value="24500">Navicular Bone of Right Foot</option>
                <option value="10014">Ninth Thoracic Vertebra</option>
                <option value="46019">Oblique Head of Left Adductor Hallucis</option>
                <option value="46122">Oblique Head of Left Adductor Pollicis</option>
                <option value="46018">Oblique Head of Right Adductor Hallucis</option>
                <option value="46121">Oblique Head of Right Adductor Pollicis</option>
                <option value="52735">Occipital Bone</option>
                <option value="76892">Omental Taenia</option>
                <option value="86035">Opponens Digiti Minimi of Left Foot</option>
                <option value="37401">Opponens Digiti Minimi of Left Hand</option>
                <option value="86034">Opponens Digiti Minimi of Right Foot</option>
                <option value="37400">Opponens Digiti Minimi of Right Hand</option>
                <option value="62045">Optic Chiasm</option>
                <option value="46783">Orbital Part of Left Orbicularis Oculi</option>
                <option value="46782">Orbital Part of Right Orbicularis Oculi</option>
                <option value="46786">Palpebral Part of Left Orbicularis Oculi</option>
                <option value="46785">Palpebral Part of Right Orbicularis Oculi</option>
                <option value="10419">Pancreatic Duct</option>
                <option value="62394">Peduncle of Midbrain</option>
                <option value="62033">Pineal Body</option>
                <option value="13889">Pituitary Gland</option>
                <option value="67943">Pons</option>
                <option value="46307">Posterior Belly of Left Digastric</option>
                <option value="46306">Posterior Belly of Right Digastric</option>
                <option value="62072">Posterior Commissure</option>
                <option value="7266">Posterior Papillary Muscle of Left Ventricle</option>
                <option value="7261">Posterior Papillary Muscle of Right Ventricle</option>
                <option value="72805">Posterior Part of Left Superior Temporal Gyrus</option>
                <option value="72804">Posterior Part of Right Superior Temporal Gyrus</option>
                <option value="9600">Prostate</option>
                <option value="43254">Proximal Phalanx of Left Big Toe</option>
                <option value="32639">Proximal Phalanx of Left Fourth Toe</option>
                <option value="71915">Proximal Phalanx of Left Index Finger</option>
                <option value="66791">Proximal Phalanx of Left Little Finger</option>
                <option value="32641">Proximal Phalanx of Left Little Toe</option>
                <option value="71908">Proximal Phalanx of Left Middle Finger</option>
                <option value="71916">Proximal Phalanx of Left Ring Finger</option>
                <option value="32635">Proximal Phalanx of Left Second Toe</option>
                <option value="32637">Proximal Phalanx of Left Third Toe</option>
                <option value="65470">Proximal Phalanx of Left Thumb</option>
                <option value="43253">Proximal Phalanx of Right Big Toe</option>
                <option value="32638">Proximal Phalanx of Right Fourth Toe</option>
                <option value="24451">Proximal Phalanx of Right Index Finger</option>
                <option value="24454">Proximal Phalanx of Right Little Finger</option>
                <option value="32640">Proximal Phalanx of Right Little Toe</option>
                <option value="24452">Proximal Phalanx of Right Middle Finger</option>
                <option value="24453">Proximal Phalanx of Right Ring Finger</option>
                <option value="32634">Proximal Phalanx of Right Second Toe</option>
                <option value="32636">Proximal Phalanx of Right Third Toe</option>
                <option value="24450">Proximal Phalanx of Right Thumb</option>
                <option value="66326">Pulmonary Artery</option>
                <option value="7246">Pulmonary Valve</option>
                <option value="66643">Pulmonary Vein</option>
                <option value="38641">Radial Head of Left Flexor Digitorum Superficialis</option>
                <option value="38640">Radial Head of Right Flexor Digitorum Superficialis</option>
                <option value="14544">Rectum</option>
                <option value="37459">Right Abductor Hallucis</option>
                <option value="37386">Right Abductor Pollicis Brevis</option>
                <option value="38516">Right Abductor Pollicis Longus</option>
                <option value="72701">Right Accessory Short Gyrus</option>
                <option value="22452">Right Adductor Brevis</option>
                <option value="22456">Right Adductor Longus</option>
                <option value="46443">Right Coccygeus</option>
                <option value="22459">Right Adductor Magnus</option>
                <option value="43886">Right Adductor Minimus</option>
                <option value="15629">Right Adrenal Gland</option>
                <option value="72832">Right Amygdala</option>
                <option value="37705">Right Anconeus</option>
                <option value="72669">Right Angular Gyrus</option>
                <option value="37668">Right Brachialis</option>
                <option value="4751">Right Brachiocephalic Vein</option>
                <option value="38486">Right Brachioradialis</option>
                <option value="46835">Right Buccinator</option>
                <option value="258847">Right Calcaneal Tendon</option>
                <option value="24497">Right Calcaneus</option>
                <option value="24446">Right Capitate</option>
                <option value="72826">Right Caudate Nucleus</option>
                <option value="81752">Right Cervical Rotator</option>
                <option value="72717">Right Cingulate Gyrus</option>
                <option value="13322">Right Clavicle</option>
                <option value="3941">Right Common Carotid Artery</option>
                <option value="14765">Right Common Iliac Artery</option>
                <option value="21387">Right Common Iliac Vein</option>
                <option value="37665">Right Coracobrachialis</option>
                <option value="46796">Right Corrugator Supercilii</option>
                <option value="24528">Right Cuboid Bone</option>
                <option value="19235">Right Deferent Duct</option>
                <option value="46829">Right Depressor Anguli Oris</option>
                <option value="46817">Right Depressor Labii Inferioris</option>
                <option value="55608">Right Depressor Septi Nasi</option>
                <option value="8283">Right Eighth Rib</option>
                <option value="8531">Right Eleventh Rib</option>
                <option value="18256">Right Epididymis</option>
                <option value="38498">Right Extensor Carpi Radialis Brevis</option>
                <option value="38495">Right Extensor Carpi Radialis Longus</option>
                <option value="38504">Right Extensor Digiti Minimi</option>
                <option value="38501">Right Extensor Digitorum</option>
                <option value="51142">Right Extensor Digitorum Brevis</option>
                <option value="22548">Right Extensor Digitorum Longus</option>
                <option value="51144">Right Extensor Hallucis Brevis</option>
                <option value="22546">Right Extensor Hallucis Longus</option>
                <option value="38525">Right Extensor Indicis</option>
                <option value="38519">Right Extensor Pollicis Brevis</option>
                <option value="38522">Right Extensor Pollicis Longus</option>
                <option value="18806">Right External Iliac Artery</option>
                <option value="18885">Right External Iliac Vein</option>
                <option value="13336">Right External Oblique</option>
                <option value="24474">Right Femur</option>
                <option value="24480">Right Fibula</option>
                <option value="22554">Right Fibularis Brevis</option>
                <option value="22552">Right Fibularis Longus</option>
                <option value="22550">Right Fibularis Tertius</option>
                <option value="8070">Right Fifth Costal Cartilage</option>
                <option value="24472">Right Fifth Metacarpal Bone</option>
                <option value="24515">Right Fifth Metatarsal Bone</option>
                <option value="8066">Right Fifth Rib</option>
                <option value="7875">Right First Costal Cartilage</option>
                <option value="24464">Right First Metacarpal Bone</option>
                <option value="24507">Right First Metatarsal Bone</option>
                <option value="7857">Right First Rib</option>
                <option value="37465">Right Flexor Accessorius</option>
                <option value="38460">Right Flexor Carpi Radialis</option>
                <option value="37461">Right Flexor Digitorum Brevis</option>
                <option value="65016">Right Flexor Digitorum Longus</option>
                <option value="38479">Right Flexor Digitorum Profundus</option>
                <option value="65014">Right Flexor Hallucis Longus</option>
                <option value="38482">Right Flexor Pollicis Longus</option>
                <option value="72924">Right Fornix of Forebrain</option>
                <option value="7976">Right Fourth Costal Cartilage</option>
                <option value="24470">Right Fourth Metacarpal Bone</option>
                <option value="24513">Right Fourth Metatarsal Bone</option>
                <option value="7957">Right Fourth Rib</option>
                <option value="46759">Right Frontalis</option>
                <option value="72689">Right Fusiform Gyrus</option>
                <option value="22336">Right Gemellus Inferior</option>
                <option value="22334">Right Gemellus Superior</option>
                <option value="46326">Right Geniohyoid</option>
                <option value="72830">Right Globus Pallidus</option>
                <option value="22328">Right Gluteus Maximus</option>
                <option value="22330">Right Gluteus Medius</option>
                <option value="22332">Right Gluteus Minimus</option>
                <option value="43883">Right Gracilis</option>
                <option value="24448">Right Hamate</option>
                <option value="16586">Right Hip Bone</option>
                <option value="72713">Right Hippocampus</option>
                <option value="23130">Right Humerus</option>
                <option value="22322">Right Iliacus</option>
                <option value="45858">Right Iliococcygeus</option>
                <option value="22744">Right Iliocostalis Cervicis</option>
                <option value="22740">Right Iliocostalis Lumborum</option>
                <option value="22742">Right Iliocostalis Thoracis</option>
                <option value="58776">Right Iliotibial Tract</option>
                <option value="73434">Right Inferior Colliculus</option>
                <option value="54737">Right Inferior Nasal Concha</option>
                <option value="72687">Right Inferior Temporal Gyrus</option>
                <option value="32547">Right Infraspinatus Muscle</option>
                <option value="21964">Right Inguinal Ligament</option>
                <option value="72977">Right Insula</option>
                <option value="24523">Right Intermediate Cuneiform Bone</option>
                <option value="258850">Right Intermediate Tendon</option>
                <option value="18809">Right Internal Iliac Artery</option>
                <option value="18887">Right Internal Iliac Vein</option>
                <option value="4754">Right Internal Jugular Vein</option>
                <option value="13892">Right Internal Oblique</option>
                <option value="7204">Right Kidney</option>
                <option value="53645">Right Lacrimal Bone</option>
                <option value="24525">Right Lateral Cuneiform Bone</option>
                <option value="73303">Right Lateral Geniculate Body</option>
                <option value="78449">Right Lateral Ventricle</option>
                <option value="13358">Right Latissimus Dorsi</option>
                <option value="46823">Right Levator Anguli Oris</option>
                <option value="46806">Right Levator Labii Superioris</option>
                <option value="46803">Right Levator Labii Superioris Alaeque Nasi</option>
                <option value="32540">Right Levator Scapulae</option>
                <option value="71194">Right Lobe of Thymus</option>
                <option value="44249">Right Long Plantar Ligament</option>
                <option value="22754">Right Longissimus Capitis</option>
                <option value="22757">Right Longissimus Cervicis</option>
                <option value="22751">Right Longissimus Thoracis</option>
                <option value="46309">Right Longus Capitis</option>
                <option value="57142">Right Lower Central Secondary Incisor Tooth</option>
                <option value="55705">Right Lower First Secondary Molar Tooth</option>
                <option value="55694">Right Lower First Secondary Premolar Tooth</option>
                <option value="57140">Right Lower Lateral Secondary Incisor Tooth</option>
                <option value="55706">Right Lower Second Secondary Molar Tooth</option>
                <option value="55695">Right Lower Second Secondary Premolar Tooth</option>
                <option value="55686">Right Lower Secondary Canine Tooth</option>
                <option value="23089">Right Lumbar Rotator</option>
                <option value="24437">Right Lunate</option>
                <option value="53649">Right Maxilla</option>
                <option value="24521">Right Medial Cuneiform Bone</option>
                <option value="73309">Right Medial Geniculate Body</option>
                <option value="49012">Right Medial Pterygoid</option>
                <option value="46826">Right Mentalis</option>
                <option value="72655">Right Middle Frontal Gyrus</option>
                <option value="72685">Right Middle Temporal Gyrus</option>
                <option value="22878">Right Multifidus</option>
                <option value="46321">Right Mylohyoid</option>
                <option value="53647">Right Nasal Bone</option>
                <option value="55606">Right Nasalis</option>
                <option value="8364">Right Ninth Rib</option>
                <option value="32536">Right Obliquus Capitis Inferior</option>
                <option value="32534">Right Obliquus Capitis Superior</option>
                <option value="22326">Right Obturator Externus</option>
                <option value="22324">Right Obturator Internus</option>
                <option value="72975">Right Occipital Lobe</option>
                <option value="46761">Right Occipitalis</option>
                <option value="13348">Right Omohyoid</option>
                <option value="37390">Right Opponens Pollicis</option>
                <option value="50875">Right Optic Nerve</option>
                <option value="62382">Right Optic Tract</option>
                <option value="53655">Right Palatine Bone</option>
                <option value="38463">Right Palmaris Longus</option>
                <option value="45856">Right Puborectalis</option>
                <option value="72705">Right Parahippocampal Gyrus</option>
                <option value="52788">Right Parietal Bone</option>
                <option value="24486">Right Patella</option>
                <option value="22450">Right Pectineus</option>
                <option value="13375">Right Pectoralis Minor</option>
                <option value="22340">Right Piriformis</option>
                <option value="24441">Right Pisiform</option>
                <option value="22560">Right Plantaris</option>
                <option value="45739">Right Platysma</option>
                <option value="22591">Right Popliteus</option>
                <option value="72665">Right Postcentral Gyrus</option>
                <option value="76994">Right Posterolateral Branch of Right Coronary Artery</option>
                <option value="72661">Right Precentral Gyrus</option>
                <option value="55610">Right Procerus</option>
                <option value="38454">Right Pronator Quadratus</option>
                <option value="22342">Right Psoas Major</option>
                <option value="45854">Right Pubococcygeus</option>
                <option value="72828">Right Putamen</option>
                <option value="22346">Right Pyramidalis</option>
                <option value="22338">Right Quadratus Femoris</option>
                <option value="22348">Right Quadratus Lumborum</option>
                <option value="23464">Right Radius</option>
                <option value="13377">Right Rectus Abdominis</option>
                <option value="46313">Right Rectus Capitis Anterior</option>
                <option value="46317">Right Rectus Capitis Lateralis</option>
                <option value="32530">Right Rectus Capitis Posterior Major</option>
                <option value="32532">Right Rectus Capitis Posterior Minor</option>
                <option value="38928">Right Rectus Femoris</option>
                <option value="14752">Right Renal Artery</option>
                <option value="14335">Right Renal Vein</option>
                <option value="13381">Right Rhomboid Major</option>
                <option value="13383">Right Rhomboid Minor</option>
                <option value="46839">Right Risorius</option>
                <option value="22354">Right Sartorius</option>
                <option value="13392">Right Scalenus Anterior</option>
                <option value="13390">Right Scalenus Medius</option>
                <option value="13388">Right Scalenus Posterior</option>
                <option value="24435">Right Scaphoid</option>
                <option value="13395">Right Scapula</option>
                <option value="7886">Right Second Costal Cartilage</option>
                <option value="24466">Right Second Metacarpal Bone</option>
                <option value="24509">Right Second Metatarsal Bone</option>
                <option value="7882">Right Second Rib</option>
                <option value="22448">Right Semimembranosus</option>
                <option value="19387">Right Seminal Vesicle</option>
                <option value="22876">Right Semispinalis Capitis</option>
                <option value="22874">Right Semispinalis Cervicis</option>
                <option value="22872">Right Semispinalis Thoracis</option>
                <option value="22358">Right Semitendinosus</option>
                <option value="13398">Right Serratus Anterior</option>
                <option value="13405">Right Serratus Posterior Inferior</option>
                <option value="13403">Right Serratus Posterior Superior</option>
                <option value="8248">Right Seventh Costal Cartilage</option>
                <option value="8229">Right Seventh Rib</option>
                <option value="8194">Right Sixth Costal Cartilage</option>
                <option value="8175">Right Sixth Rib</option>
                <option value="22558">Right Soleus</option>
                <option value="22779">Right Spinalis Thoracis</option>
                <option value="22728">Right Splenius Capitis</option>
                <option value="22726">Right Splenius Cervicis</option>
                <option value="13408">Right Sternocleidomastoid</option>
                <option value="13346">Right Sternohyoid</option>
                <option value="13350">Right Sternothyroid</option>
                <option value="73413">Right Stria Medullaris of Thalamus</option>
                <option value="72939">Right Stria Terminalis</option>
                <option value="45826">Right Stylohyoid</option>
                <option value="3953">Right Subclavian Artery</option>
                <option value="4755">Right Subclavian Vein</option>
                <option value="13412">Right Subclavius</option>
                <option value="13414">Right Subscapularis</option>
                <option value="73422">Right Superior Colliculus</option>
                <option value="72653">Right Superior Frontal Gyrus</option>
                <option value="38513">Right Supinator</option>
                <option value="72667">Right Supramarginal Gyrus</option>
                <option value="32544">Right Supraspinatus</option>
                <option value="24482">Right Talus</option>
                <option value="52738">Right Temporal Bone</option>
                <option value="49007">Right Temporalis</option>
                <option value="46763">Right Temporoparietalis</option>
                <option value="22425">Right Tensor Fasciae Latae</option>
                <option value="8445">Right Tenth Rib</option>
                <option value="32551">Right Teres Major</option>
                <option value="32553">Right Teres Minor</option>
                <option value="7211">Right Testis</option>
                <option value="258714">Right Thalamus</option>
                <option value="7913">Right Third Costal Cartilage</option>
                <option value="24468">Right Third Metacarpal Bone</option>
                <option value="24511">Right Third Metatarsal Bone</option>
                <option value="7909">Right Third Rib</option>
                <option value="13352">Right Thyrohyoid</option>
                <option value="24477">Right Tibia</option>
                <option value="22544">Right Tibialis Anterior</option>
                <option value="65018">Right Tibialis Posterior</option>
                <option value="22344">Right Transversus Abdominis</option>
                <option value="9761">Right Transversus Thoracis</option>
                <option value="24443">Right Trapezium</option>
                <option value="23725">Right Trapezoid</option>
                <option value="24439">Right Triquetral</option>
                <option value="8533">Right Twelfth Rib</option>
                <option value="23467">Right Ulna</option>
                <option value="55681">Right Upper Central Secondary Incisor Tooth</option>
                <option value="55698">Right Upper First Secondary Molar Tooth</option>
                <option value="55689">Right Upper First Secondary Premolar Tooth</option>
                <option value="9187">Second Thoracic Vertebra</option>
                <option value="55680">Right Upper Lateral Secondary Incisor Tooth</option>
                <option value="55697">Right Upper Second Secondary Molar Tooth</option>
                <option value="55688">Right Upper Second Secondary Premolar Tooth</option>
                <option value="55798">Right Upper Secondary Canine Tooth</option>
                <option value="15571">Right Ureter</option>
                <option value="38934">Right Vastus Intermedius</option>
                <option value="38930">Right Vastus Lateralis</option>
                <option value="38932">Right Vastus Medialis</option>
                <option value="52892">Right Zygomatic Bone</option>
                <option value="46812">Right Zygomaticus Major</option>
                <option value="46814">Right Zygomaticus Minor</option>
                <option value="16202">Sacrum</option>
                <option value="13073">Second Lumbar Vertebra</option>
                <option value="37720">Second Lumbrical of Left Foot</option>
                <option value="37719">Second Lumbrical of Right Foot</option>
                <option value="37744">Second Plantar Interosseous of Left Foot</option>
                <option value="37743">Second Plantar Interosseous of Right Foot</option>
                <option value="7262">Septal Papillary Muscle of Right Ventricle</option>
                <option value="61844">Septum Pellucidum</option>
                <option value="45098">Sesamoid Bone of Left Foot</option>
                <option value="45097">Sesamoid Bone of Right Foot</option>
                <option value="71567">Set of Anterior Cardiac Veins</option>
                <option value="71442">Set of Anterior Cervical Intertransversarii</option>
                <option value="74141">Set of Dorsal Interossei of Left Foot</option>
                <option value="42405">Set of Dorsal Interossei of Left Hand</option>
                <option value="74140">Set of Dorsal Interossei of Right Foot</option>
                <option value="42404">Set of Dorsal Interossei of Right Hand</option>
                <option value="71098">Set of Eyebrows</option>
                <option value="70751">Set of Head Hairs</option>
                <option value="71309">Set of Interspinales Cervicis</option>
                <option value="71307">Set of Interspinales Lumborum</option>
                <option value="71308">Set of Interspinales Thoracis</option>
                <option value="71670">Set of Interventricular Septal Branches of Left Coronary Artery</option>
                <option value="71669">Set of Interventricular Septal Branches of Right Coronary Artery</option>
                <option value="71444">Set of Lateral Lumbar Intertransversarius Muscles</option>
                <option value="74078">Set of Left Levatores Costarum Breves</option>
                <option value="74076">Set of Left Levatores Costarum Longi</option>
                <option value="42399">Set of Lumbricals of Left Hand</option>
                <option value="42398">Set of Lumbricals of Right Hand</option>
                <option value="76775">Set of Medial Lumbar Intertransversarius Muscles</option>
                <option value="71704">Set of Nasal Cartilages</option>
                <option value="42403">Set of Palmar Interossei of Left Hand</option>
                <option value="42402">Set of Palmar Interossei of Right Hand</option>
                <option value="71443">Set of Posterior Cervical Intertransversarii</option>
                <option value="76751">Set of Posterior Veins of Left Ventricle</option>
                <option value="70754">Set of Pubic Hairs</option>
                <option value="74077">Set of Right Levatores Costarum Breves</option>
                <option value="74075">Set of Right Levatores Costarum Longi</option>
                <option value="12525">Seventh Cervical Vertebra</option>
                <option value="9968">Seventh Thoracic Vertebra</option>
                <option value="37685">Short Head of Left Biceps Brachii</option>
                <option value="45892">Short Head of Left Biceps Femoris</option>
                <option value="37684">Short Head of Right Biceps Brachii</option>
                <option value="45891">Short Head of Right Biceps Femoris</option>
                <option value="12524">Sixth Cervical Vertebra</option>
                <option value="9945">Sixth Thoracic Vertebra</option>
                <option value="7163">Skin</option>
                <option value="52736">Sphenoid Bone</option>
                <option value="34685">Spinal Part of Left Deltoid</option>
                <option value="34684">Spinal Part of Right Deltoid</option>
                <option value="7196">Spleen</option>
                <option value="14773">Splenic Artery</option>
                <option value="14331">Splenic Vein</option>
                <option value="4685">Stem of Left Coronary Artery</option>
                <option value="79980">Sternocostal Part of Left Pectoralis Major</option>
                <option value="79979">Sternocostal Part of Right Pectoralis Major</option>
                <option value="7148">Stomach</option>
                <option value="65199">Superficial Head of Left Flexor Pollicis Brevis</option>
                <option value="65198">Superficial Head of Right Flexor Pollicis Brevis</option>
                <option value="49002">Superficial Part of Left Masseter</option>
                <option value="49001">Superficial Part of Right Masseter</option>
                <option value="14749">Superior Mesenteric Artery</option>
                <option value="14332">Superior Mesenteric Vein</option>
                <option value="46284">Superior Oblique Part of Left Longus Colli</option>
                <option value="46283">Superior Oblique Part of Right Longus Colli</option>
                <option value="4720">Superior Vena Cava</option>
                <option value="46442">Tendinous Arch of Levator Ani</option>
                <option value="10037">Tenth Thoracic Vertebra</option>
                <option value="12521">Third Cervical Vertebra</option>
                <option value="13074">Third Lumbar Vertebra</option>
                <option value="37486">Third Lumbrical of Left Foot</option>
                <option value="37485">Third Lumbrical of Right Foot</option>
                <option value="37742">Third Plantar Interosseous of Left Foot</option>
                <option value="37741">Third Plantar Interosseous of Right Foot</option>
                <option value="9209">Third Thoracic Vertebra</option>
                <option value="78454">Third Ventricle</option>
                <option value="23083">Thoracic Rotator</option>
                <option value="55099">Thyroid Cartilage</option>
                <option value="7394">Trachea</option>
                <option value="46021">Transverse Head of Left Adductor Hallucis</option>
                <option value="46124">Transverse Head of Left Adductor Pollicis</option>
                <option value="46020">Transverse Head of Right Adductor Hallucis</option>
                <option value="46123">Transverse Head of Right Adductor Pollicis</option>
                <option value="33585">Transverse Part of Left Trapezius</option>
                <option value="33584">Transverse Part of Right Trapezius</option>
                <option value="7234">Tricuspid Valve</option>
                <option value="3802">Trunk of Right Coronary Artery</option>
                <option value="62327">Tuber Cinereum</option>
                <option value="10081">Twelfth Thoracic Vertebra</option>
                <option value="38620">Ulnar Head of Left Flexor Carpi Ulnaris</option>
                <option value="38563">Ulnar Head of Left Pronator Teres</option>
                <option value="38619">Ulnar Head of Right Flexor Carpi Ulnaris</option>
                <option value="38562">Ulnar Head of Right Pronator Teres</option>
                <option value="49025">Upper Head of Left Lateral Pterygoid</option>
                <option value="49024">Upper Head of Right Lateral Pterygoid</option>
                <option value="7370">Upper Lobe of Left Lung</option>
                <option value="7333">Upper Lobe of Right Lung</option>
                <option value="19667">Urethra</option>
                <option value="15900">Urinary Bladder</option>
                <option value="46286">Vertical Intermediate Part of Left Longus Colli</option>
                <option value="46285">Vertical Intermediate Part of Right Longus Colli</option>
                <option value="9710">Vomer</option>
                <option value="7274">Wall of Heart</option>
                <option value="61822">White Matter Structure of Cerebral Hemisphere</option>
                <option value="7488">Xiphoid Process</option>
            </select>
            <input style="vertical-align: top;" value="Add Entity" onclick="addEntityKnowledge()" id="addEntityButton" type="button"/><br/>
        </div>
        
        <div>
            <div>
                <select id="entityRemoveSelect" size="12" multiple="multiple" style="height:250px;">
                    <c:forEach var="item" items="${entitySubItems}">
                        <option value="${item.nodeId}">${item.fmaLabel}</option>    
                    </c:forEach>
                </select><br/>
                &#160;<a href="tutoring/curriculumItem/${curriculumItem.nodeId}/build/fromQuery">Add entities from query results</a><br/>
                &#160;<a href="tutoring/curriculumItem/${curriculumItem.nodeId}/build/fromAssetSet">Add entities from asset set</a>            
            </div>
            <div>
                <input style="vertical-align: top;" value="Remove Entities" onclick="removeEntityKnowledge()" id="removeEntityButton" type="button"/>
                <br />            
                <div class="text" id="entityMessage" style="margin: 6px 0px 0px 2px;">&#160;</div>
            </div>
        </div>
    </fieldset>
</div>


<div class="glue">
    <fieldset>
        <legend>Labels</legend>
        
        <div>
            <div class="text" style="margin: 2px 2px 6px 6px;">
                <b>Include label knowledge?</b> If label knowledge is not included, this curriculum item will will assume that students 
                can recognize and name the entities selected above.<br/>
            </div>
            <select id="labelToggleSelect" onchange="toggleLabelKnowledge();">
                <c:choose>
                    <c:when test="${labelKnowledgeIncluded}">
                        <option value="true" selected="true">Yes</option>
                        <option value="false">No</option>
                    </c:when>
                    <c:otherwise>
                        <option value="true">Yes</option>
                        <option value="false" selected="true">No</option>
                    </c:otherwise>
                </c:choose>
            </select>
            <br clear="all"/>
            <div class="text" id="labelMessage" style="margin: 2px 2px 6px 6px;">
                <c:choose>
                    <c:when test="${labelKnowledgeIncluded}">Label knowledge included</c:when>
                    <c:otherwise>Label knowledge not included</c:otherwise>
                </c:choose>
            </div>
        </div>
    </fieldset>
</div>


<div class="glue">
    <fieldset>
        <legend>Relations</legend>

        <div>
            <select id="relationAddSelect">
                <option value="fma:articulates_with">fma:articulates_with</option>
                <option value="fma:constitutional_part">fma:constitutional_part</option>
                <option value="fma:label">fma:label</option>
                <option value="fma:member_of">fma:member_of</option>
                <option value="fma:muscle_origin">fma:muscle_origin</option>
                <option value="fma:muscle_insertion">fma:muscle_insertion</option>
                <option value="fma:nerve_supply">fma:nerve_supply</option>
            </select>
            <input style="vertical-align: top;" value="Add Relation" onclick="addRelationKnowledge()" id="addRelationButton" type="button"/>
        </div>
        
        <div>
            <select id="relationRemoveSelect" style="height:250px;" multiple="multiple" size="12">
                <c:forEach var="item" items="${relationSubItems}">
                    <option value="${item.nodeId}">${item.namespace}:${item.name}</option>    
                </c:forEach>
            </select>
            <div>
                <input style="vertical-align: top;" value="Remove Relations" onclick="removeRelationKnowledge()" id="removeRelationButton" type="button"/>
                <br clear="all"/>
                <div class="text" id="relationMessage" style="margin: 6px 0px 0px 2px;">&#160;</div>
            </div>
        </div>
    </fieldset>
</div>

</jsp:root>
